filebeat.prospectors:

- input_type: log

  paths:
    - "/logs/cron.log"

  # Exclude lines. A list of regular expressions to match. It drops the lines that
  # match any regular expression from the list.
  exclude_lines: ["Updated timestamp for job"]

  fields:
    service: cron

  fields_under_root: true


- input_type: log

  paths:
    - "/logs/apache.log"

  fields:
    service: apache

  fields_under_root: true

output.logstash:
  hosts: ["logstash-demo:5043"]
