version: '2'
services:
    filebeat:
        image: docker.elastic.co/beats/filebeat:5.5.2
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./filebeat/data/:/usr/share/filebeat/data
            - ./logs:/logs
        container_name: filebeat-demo
        hostname: filebeat-demo
        command: /usr/share/filebeat/filebeat -e -d "publish"